import { withMetadata } from 'src/packages/utils/metadata';
import RootLayout from 'src/packages/components/layouts/root';
import 'src/styles/globals.css';

export const metadata = withMetadata({
  title: 'Create Next App',
  description: 'Generated by create next app',
});

export default RootLayout;
