import RootLayout from 'packages/components/layouts/root.layout';
import { withMetadata } from 'packages/utils/metadata';
import 'styles/globals.css';

export const metadata = withMetadata({
  title: 'Create Next App',
  description: 'Generated by create next app',
});

export default RootLayout;
